2020-08-01 10:15:01,208 ERROR: Exception on /explore [GET] [in /home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vasco/Desktop/wswebdev/microblog/app/main/routes.py", line 59, in explore
    return render_template('index.html', title=_('Explore'),
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/vasco/Desktop/wswebdev/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/vasco/Desktop/wswebdev/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/vasco/Desktop/wswebdev/microblog/app/templates/base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2020-08-01 10:18:18,157 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:74]
2020-08-01 10:18:20,574 ERROR: Exception on /explore [GET] [in /home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vasco/Desktop/wswebdev/microblog/app/main/routes.py", line 59, in explore
    return render_template('index.html', title=_('Explore'),
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/vasco/Desktop/wswebdev/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/vasco/Desktop/wswebdev/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/vasco/Desktop/wswebdev/microblog/app/templates/base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2020-08-01 10:18:42,150 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:74]
